### ISSUE TITLE
C Indicator

### ISSUE THREAD

**Issue by timcullen** [spmason/qif2json#5]
For what its worth I think the C indicator stands for 'Cleared Status'

see here https://www.w3.org/2000/10/swap/pim/qif-doc/QIF-doc.htm

**Comment by spmason** [comment]
Right you are - I'd happily accept a pr to fix this, or I'll likely have time to do it myself over the next couple of days

Sounds like a backward-incompatible change so it would require a major version bump. Might as well go through other fields in that spec and make sure the naming matches up at the same time

**Comment by timcullen** [comment]
I think you're right its probably a breaking change.  Perhaps a route to managing that might be to have the Case 'C' code set both transaction.accounttype and transaction.clearedStatus variables?

**Comment by spmason** [comment]
I think it's fine to make this a breaking change - it just means the next version will be `0.2.0`, which seems reasonable given the changes I'm making

I've made this change now to master, so I'm going to close this. I'll try to release 0.2.0 tonight
