### ISSUE TITLE
Unkown Detail Code: E

### ISSUE THREAD

**Issue by benjaminprojas** [spmason/qif2json#8]
Was just trying to parse a QIF file and received this error: `Unkown Detail Code: E`

Looking at the source code, E is a valid detail code, so not sure what the problem might be.  

I am running this in Windows Subsystem Linux so maybe its from that? 

Any help is appreciated, thanks!

**Comment by benjaminprojas** [comment]
Just realized that my local qif2json from npm does not have the detail code E as a valid option. Any chance you can push out the latest to npm? Thanks!

**Comment by spmason** [comment]
Sorry about that - 0.3.0 pushed now

**Comment by benjaminprojas** [comment]
Thanks! Works perfectly.
